Repository VulnerabilityHistoryProject/systemd-vulnerabilities, pull requests merged in 2021-11, with the labels that each got.

#32 CVE-2018-16864
  cves/CVE-2018-16864.yml
Labels: cohort E

#31 CVE-2018-21029
  cves/CVE-2018-21029.yml
Labels: cohort E

#30 CVE-2015-7510
  cves/CVE-2015-7510.yml
Labels: cohort C

#28 CVE-2018-15687
  cves/CVE-2018-15687.yml
Labels: cohort D

#27 CVE-2017-9217
  cves/CVE-2017-9217.yml
Labels: cohort G

#26 Update CVE-2020-13529.yml
  cves/CVE-2020-13529.yml
Labels: cohort F

#25 CVE-2018-16865
  cves/CVE-2018-16865.yml
Labels: cohort E

#24 CVE-2018-1049
  cves/CVE-2018-1049.yml
Labels: cohort A

#23 CVE-2018-20839
  cves/CVE-2018-20839.yml
Labels: cohort E

#4 CVE-2017-15908
  cves/CVE-2017-15908.yml
Labels: cohort A

#21 CVE-2020-13776 (Updated)
  .vs/slnx.sqlite
  .vs/systemd-vulnerabilities/v16/.suo
  cves/CVE-2020-13776.yml
Labels: cohort F

#20 CVE-2013-4393
  cves/CVE-2013-4393.yml
Labels: cohort C

#19 CVE-2018-16866
  cves/CVE-2018-16866.yml
Labels: cohort D

#18 CVE-2019-6454
  cves/CVE-2019-6454.yml
Labels: cohort B

#13 CVE-2013-4392
  cves/CVE-2013-4392.yml
Labels: cohort G

#12 CVE-2013-4394
  cves/CVE-2013-4394.yml
Labels: cohort D

#11 CVE-2019-3843
  cves/CVE-2019-3843.yml
Labels: cohort C

#9 CVE-2018-15686
  cves/CVE-2018-15686.yml
Labels: cohort A

#8 CVE-2017-9445
  cves/CVE-2017-9445.yml
Labels: cohort G

#7 CVE-2019-3844
  cves/CVE-2019-3844.yml
Labels: cohort A

#6 CVE-2020-1712
  cves/CVE-2020-1712.yml
Labels: cohort C

#5 CVE-2018-15688: dhcp6 client buffer overflow
  cves/CVE-2018-15688.yml
Labels: cohort B
